Resource Management Detection (RM_Detect) Framework - its main goals right now is to abstract out the testing of each resource manager - all information is provided in the component that comes with the resource manager package in its scripts/ directory, this perl module will then be copied to lib/OSCAR/OCA/RM_Detect upon installation - if you do not install a resource manager, the parallel library packages will _not_ be tested - each parallel library package that requires testing via the resource manager will provide a rm_script.<pkg> script which will perform the bulk of the testing required by the package - it should work for all resource managers - more discussions on this topic can be found here: http://sourceforge.net/search/?forum_id=1363&group_id=9368&words=rm_detect&type_of_search=mlists
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@4353 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: c60b3f3eb9d1ab37a5f4bd816e7790032da05ffe [formerly 27a747de6238b3e19e53607a1eafe38d61a043c4] [formerly 48a86c1b34e0995c07e7a756c94b4b295d2dbe02 [formerly cb4bfdb097f4a7cf8b1d8ddacc68ff3ab7e5f4af]] [formerly e7384e1d221848b62c8023d097daa08dca9a296d [formerly 196ea28cd0b9debd8d5e175023a88f03992cec9e] [formerly 5acc28d271df046b72c05dffe6221c861d3f3c6e [formerly f334a50384613908cd745c0ec257dd3f68a561ee]]]
Former-commit-id: 345c38d2641a945f42a3bef01b517e1601c9cd40 [formerly 95c0838e8f7386278c63be66133ed65a16f7cca0] [formerly e0854df4742c85187f715b13a243544ea2d82440 [formerly 7bc4c1ebd55c1cbe7e91286cbb62f16f7385d15f]]
Former-commit-id: 9b816d6896761845ef5d1b162a3827a5c76bea21 [formerly d64d59b5c198dff5a1edbfefc556f5e477d4aae2]
Former-commit-id: 5548acc804044127290fd4161d0b1c0717dbe29d

diff --git a/packages/lam/testing/test_user b/packages/lam/testing/test_user
--- a/packages/lam/testing/test_user
+++ b/packages/lam/testing/test_user
@@ -7,22 +7,31 @@
 # information, see the COPYING file in the top level directory of the
 # OSCAR source distribution.
 
-# $Id: test_user,v 1.2 2002/10/31 15:47:17 jsquyres Exp $
+# $Id$
 #
 # Authors: Jason Brechin
 #          Jeremy Enos
 #	   Bernard Li
 #          Jeffrey M. Squyres
 
-if test -e /usr/share/doc/openpbs*; then
-   scheduler="PBS"
-else
-   scheduler="Torque"
+rm=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{rm}'`
+
+if [ $? -gt 0 ]; then
+   echo "Cannot determine resource manager for system, cannot continue."
+   exit
 fi
+
+if test $rm = "None"; then
+   exit
+fi
+
+rm_test=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{test}' | awk -F "/" {'print \$NF'}`
+#rm_jobscript=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{jobscript}'`
+rm_jobscript="rm_script"
 
 cd
 clients=`echo $@ | wc -w`
-testprint_label="LAM/MPI (via $scheduler)"
+testprint_label="LAM/MPI (via $rm)"
 
 # Sanity check (somewhat overkill, but safe = good): check to see that
 # there is a LAM installed.
@@ -78,7 +87,7 @@ done
 
 # Now run the test (results will be printed by the test itself)
 
-$HOME/pbs_test $clients 1 $HOME/lam/pbs_script.lam "Hello" \
+$HOME/$rm_test $clients 1 $HOME/lam/$rm_jobscript.lam "Hello" \
     $HOME/lam/lamtest 3 "$testprint_label"
 exit_status=$?
 
diff --git a/packages/mpich/testing/test_user b/packages/mpich/testing/test_user
--- a/packages/mpich/testing/test_user
+++ b/packages/mpich/testing/test_user
@@ -7,22 +7,30 @@
 # information, see the COPYING file in the top level directory of the
 # OSCAR source distribution.
 
-# $Id: test_user,v 1.3 2003/05/06 20:59:17 brechin Exp $
+# $Id$
 #
 # Authors: Jason Brechin
 #          Jeremy Enos
-#	   Bernard Li
+#          Bernard Li
 #          Jeffrey M. Squyres
 
-if test -e /usr/share/doc/openpbs*; then
-   scheduler="PBS"
-else
-   scheduler="Torque"
+rm=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{rm}'`
+
+if [ $? -gt 0 ]; then
+   echo "Cannot determine resource manager for system, cannot continue."
+   exit
 fi
+
+if test $rm = "None"; then
+   exit
+fi
+
+rm_test=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{test}' | awk -F "/" {'print \$NF'}`
+rm_jobscript=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{jobscript}'`
 
 cd
 clients=`echo $@ | wc -w`
-testprint_label="MPICH (via $scheduler)"
+testprint_label="MPICH (via $rm)"
 
 # Sanity check (somewhat overkill, but safe = good): check to see that
 # there is a MPICH installed.
@@ -77,7 +85,7 @@ done
 ############################################################################
 # Now run the test (results will be printed by the test itself)
 
-$HOME/pbs_test $clients 1 $HOME/mpich/pbs_script.mpich "Hello" \
+$HOME/$rm_test $clients 1 $HOME/mpich/$rm_jobscript.mpich "Hello" \
     $HOME/mpich/mpichtest 3 "$testprint_label"
 exit_status=$?
 
diff --git a/packages/pvm/testing/test_user b/packages/pvm/testing/test_user
--- a/packages/pvm/testing/test_user
+++ b/packages/pvm/testing/test_user
@@ -2,31 +2,37 @@
 #
 # Copyright (c) 2002 The Trustees of Indiana University.  
 #                    All rights reserved.
-#		2005 Canada's Michael Smith Genome Sciences Centre
-#		     All rights reserved.
 #
 # This file is part of the OSCAR software package.  For license
 # information, see the COPYING file in the top level directory of the
 # OSCAR source distribution.
 
-# $Id: test_user,v 1.3 2002/10/31 21:18:52 brechin Exp $
+# $Id$
 #
 # Authors: Jason Brechin
 #          Jeremy Enos
 #	   Bernard Li
 
+rm=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{rm}'`
 
-if test -e /usr/share/doc/openpbs*; then
-   scheduler="PBS"
-else
-   scheduler="Torque"
+if [ $? -gt 0 ]; then
+   echo "Cannot determine resource manager for system, cannot continue."
+   exit 
 fi
+
+if test $rm = "None"; then
+   exit
+fi
+
+rm_test=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{test}' | awk -F "/" {'print \$NF'}`
+#rm_jobscript=`perl -e 'use lib "$ENV{OSCAR_HOME}/lib"; use OSCAR::OCA::RM_Detect; OSCAR::OCA::RM_Detect::open(); my $ident = $RM_Detect->{query}(); print $ident->{jobscript}'`
+rm_jobscript="rm_script"
 
 cd $HOME
 clients=`echo $@ | wc -w`
 
-$HOME/pbs_test $clients 1 $HOME/pvm/pbs_script.pvm "SUCCESSFUL" \
-    $HOME/pvm/pvmtest 3 "PVM (via $scheduler)"
+$HOME/$rm_test $clients 1 $HOME/pvm/$rm_jobscript.pvm "SUCCESSFUL" \
+    $HOME/pvm/pvmtest 3 "PVM (via $rm)"
 exit_status=$?
 
 # All done
