Modified such that .pm and .pl are compiled using generalized rules, eliminating specific rules.
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@2473 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 4c358bcd974aebc9431956bcd4e19058523c1164 [formerly d2a76934a1537caa82998d0b829a9dac317c0d5c] [formerly a71631087aa721b03804b94a48d9ae942291b99f [formerly b3aa1f791bdd176d5d1fc6b1bf729fd707769988]]
Former-commit-id: 8c3abe1636aa6360f54f1d39452af77c55b30fbe [formerly a6011336ba1dedabb30cf10e7b418efdb578b2a9]
Former-commit-id: b3f5d36732ffe365f08826d5f8fed0468ff79f1c

diff --git a/src/NodeMgmt/Makefile.am b/src/NodeMgmt/Makefile.am
--- a/src/NodeMgmt/Makefile.am
+++ b/src/NodeMgmt/Makefile.am
@@ -1,63 +1,79 @@
-PUIC		= @PUIC@
-PERL_CW		= @PERL@ -cw
+# List the binaries needed by the Makefile
+PUIC		=	@PUIC@
+PERL_CW		=	@PERL@ -cw
+RM		=	/bin/rm -f
 
-pms		= \
-		nodesettingsDialog.pm \
-		nodemgmtTable.pm \
-		nodemgmtDialog.pm
+# Enter the filename of the Perl script to be run
+EXECUTABLE	=	NodeMgmtDialog.pl
 
-pls		= nodemgmtDialog.pl
+# Enter the filenames of Perl modules which are to be generated by PUIC
+pms		=	NodeMgmtDialog.pm \
+			NodeSettingsDialog.pm
 
-uis		= \
-		nodemgmtdialog.ui \
-		nodesettingsdialog.ui
+# Enter the filenames of Perl scripts which are to be generated by PUIC
+pls		=	NodeMgmtDialog.pl
 
-uihs		= \
-		nodemgmtdialog.ui.h \
-		nodesettingsdialog.ui.h
+# Enter the filenams of Perl modules which DO NOT need to be compiled
+static_pms	=	NodeMgmtTable.pm
 
-# These are items to be distributed
-EXTRA_DIST		= $(pms) $(pls) $(uis) $(uihs) GUI.xml
+# Enter the filenams of Perl scripts which DO NOT need to be compiled
+static_pls	=	
 
-instdir			= $(prefix)/Installer/NodeMgmt
-inst_SCRIPTS		= $(pls) $(pms)
-inst_DATA		= GUI.xml
+COMPILEDTARGET	=	$(pms) $(pls)
+STATICTARGET	=	$(static_pms) $(static_pls)
+ALLTARGET	=	$(COMPILEDTARGET) $(STATICTARGET)
 
-nodemgmtDialog.pl: nodemgmtdialog.ui.h nodemgmtdialog.ui $(pms)
-	$(PUIC) -x -o nodemgmtDialog.pl nodemgmtdialog.ui
+# These are items to be distributed, i.e. put into the tarball
+EXTRA_DIST		=	$(ALLTARGET) GUI.xml
 
-nodemgmtDialog.pm: nodemgmtdialog.ui.h nodemgmtdialog.ui nodesettingsDialog.pm nodemgmtTable.pm 
-	$(PUIC) -o nodemgmtDialog.pm nodemgmtdialog.ui
+# Enter the name of the target directory for files during a 'make install'
+instdir			=	$(prefix)/Installer/NodeMgmt
+inst_SCRIPTS		=	$(ALLTARGET)
+# Enter any extra files which need to go into the install directory
+inst_DATA		=	GUI.xml
 
-nodesettingsDialog.pm: nodesettingsdialog.ui nodesettingsdialog.ui.h
-	$(PUIC) -o nodesettingsDialog.pm nodesettingsdialog.ui
+# Enter any extra make rules for files which don't have a default make rule
 
-# Hook target that Automake runs at the end of its own internal
-# "clean" target.
-clean-local:
-	rm -f nodemgmtDialog.pm nodesettingsDialog.pm $(pls)
+# May need to add extra stuff here, such as creating symbolic links
+all-local:	$(COMPILEDTARGET)
+		ln -sf ../Installer/images; \
+		cd ../Installer; ln -sf ../NodeMgmt
 
-all-local: $(pls) $(pms)
-#echo "Fixing QWidgetStack problem"
-#perl -pi -e 's/QWidgetStack/Qt::WidgetStack/' *.p*
+### SHOULDN'T NEED TO CHANGE ANYTHING BELOW HERE!
 
-check-local: $(pls) $(pms)
-	@err=0; \
-	for myfile in $(pls) $(pms); do \
-	  $(PERL_CW) $$myfile; \
-	  if [ $$? -ne 0 ]; then \
-	    err=1; \
-	  fi; \
-	done; \
-	if [ $$err -eq 1 ]; then \
-	  echo "ERROR IN BUILT CODE!!!"; \
-	  exit 1; \
-	else \
-	  echo "OK"; \
-	fi
+# General rule to make a .pm from a .ui
+.ui.pm:	$<.h $<
+	@ $(PUIC) -o $@ $<
 
-run: nodemgmtDialog.pl
-	perl ./nodemgmtDialog.pl
+# General rule to make a .pl from a .ui
+.ui.pl:	$<.h $<
+	@ $(PUIC) -x -o $@ $<
 
-debug: nodemgmtDialog.pl
-	perl -MQt::debug=calls,gc,ambiguous,verbose ./nodemgmtDialog.pl
+# Hook target that Automake runs at the end of its own internal "clean" target.
+clean-local:	
+	$(RM) $(COMPILEDTARGET)
+
+# Checks to see if the Perl modules and scripts pass a syntax check
+check-local:	$(ALLTARGET)
+		@err=0; \
+		for myfile in $(ALLTARGET); do \
+		  $(PERL_CW) $$myfile; \
+		  if [ $$? -ne 0 ]; then \
+		    err=1; \
+		  fi; \
+		done; \
+		if [ $$err -eq 1 ]; then \
+		  echo "ERROR IN BUILT CODE!!!"; \
+		  exit 1; \
+		else \
+		  echo "OK"; \
+		fi
+
+# Runs the main Perl script, but only works from the current directory
+run:		$(EXECUTABLE)
+		perl ./$(EXECUTABLE)
+
+# Same as 'make run', but output LOTS of debugging information
+debug:		$(EXECUTABLE)
+		perl -MQt::debug=calls,gc,ambiguous,verbose ./$(EXECUTABLE)
+
