- Fix for priority 9 bug 1266927 - Ganglia now has 2 tests :- 1) ganglia setup test    - original test using gstat with Erich's added functionality to match      domain pattern so we are just counting the gmonds from the OSCAR      cluster 2) ganglia node count test    - more stringent test which will fail if there are non-OSCAR cluster      gmonds running in the same subnet/switch    - it is okay to fail this test, ganglia is confirmed to be running as      long as the first test passes...
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@3740 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 4ab6caa851ea779eb0d5244a4ec8a8b8d68daef4 [formerly 0eb56f9f25cdafe9e2533c93b0b29a64fb66e9d4] [formerly 5d27710d436e86961a47da5ae4323cfc3dcb6291 [formerly 8d989d46dcc8c133a16e23f87bc3866840a401d9]] [formerly 06211338395dcde8f2dbff90c45558e5ebf1b1a4 [formerly a2d76b301dd0d68a615afae6e5f1a194964706ab] [formerly 981813b257e00d4527ae900cc9a03a56d6bbf4b9 [formerly 9b8d05f234f5eca35c570b9ebbce15d5e6a6b075]]]
Former-commit-id: ab07783b8b0a3fcc387098c3270325b390d5007d [formerly c8dc699f0d6357fd78bba8686d0b3cde39708637] [formerly f47f2c3814ac50fd5f8f141b5dc01f6fdd9059d0 [formerly 0bcd1fd3f346ff7dfb6f9574b35ea34ed2881de8]]
Former-commit-id: 6125db9a4ee94a6cc3e6f7b89ab25bf665be32ed [formerly 335f8bdb72d9e7c68a2e3267b676f09d3e625ce8]
Former-commit-id: 60f7b508f2698b3f9c330a5f95cf9b61d8019936

diff --git a/packages/ganglia/testing/test_user b/packages/ganglia/testing/test_user
--- a/packages/ganglia/testing/test_user
+++ b/packages/ganglia/testing/test_user
@@ -20,7 +20,15 @@
 # (C)opyright Bernard Li <bli@bcgsc.ca>
 #             Erich Focht <efocht@hpce.nec.com>
 
-log=ganglia.err
+log=ganglia/ganglia.err
+
+# remove old log file
+if test -f $log
+then
+  rm -rf ganglia/ganglia.err
+fi
+
+label="Ganglia setup test"
 
 # Get number of args (nodes)
 clients=`echo $@ | wc -w`
@@ -30,19 +38,42 @@ numhosts=`expr $clients + 1`
 
 # use gstat to determine number of hosts ganglia has detected 
 pattern=`hostname`"|"`perl -e "print join(\"|\",split(\" +\",\"$@\"));"`
+
+# simple test which counts the number of detected nodes (via gstat) with
+# the number of expected nodes (from argument)
+# the nodes detected have to match a certain pattern (belonging to the
+# cluster) and thus will pass even if you have other gmonds running on the
+# same network but not belonging to the same data source
 hosts=`gstat --all | egrep -c "^($pattern)$"`
 
 if [ $hosts -eq $numhosts ]
 then
-  $OSCAR_TESTPRINT --label "Ganglia test" -p
+  $OSCAR_TESTPRINT --label "$label" -p
 else
   echo "Client nodes: $@" > $log
   echo "Match pattern: $pattern" >> $log
   echo "Number of hosts matched: $hosts" >> $log
   echo "Gstat output:" >> $log
   gstat --all >> $log
-  $OSCAR_TESTPRINT --label "Ganglia test" -f
+  echo -e "\nThe number of nodes expected is different from the number of nodes detected.\nCheck to see if gmond is running on all your nodes and make sure that you\nare not having any network issues." >> $log
+  $OSCAR_TESTPRINT --label "$label" -f
   exit 1
 fi
 
+# more stringent test, will fail if number of detected nodes > expected nodes
+# this is a hard count and does not do any pattern matching - this is used to
+# notify users of renegade nodes in their OSCAR ganglia setup - failing this
+# test is not fatal
+hosts=`gstat | grep 'Hosts' | head -n 1 | awk {'print $2'}`
+
+label="Ganglia node count test"
+
+if [ $hosts -eq $numhosts ]
+then
+  $OSCAR_TESTPRINT --label "$label" -p
+else
+  echo -e "Ganglia expects to have $numhosts nodes but found $hosts nodes.  Please check to see\nif there are non-OSCAR cluster gmond(s) running on the same network/switch\nand correct the problem.  This test failure is not catastrophic, it\nis safe to ignore if \"Ganglia setup test\" succeeds." > $log
+  $OSCAR_TESTPRINT --label "$label" -f
+  exit 1
+fi
 exit 0
