- A few minor shell fixes - Remove the explicit ". /etc/profile" at the top; the relevant parts of   /etc/profile should be invoked automatically, and running it explicitly   seems to cause harm (with switcher)
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@1361 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 361b02bfd6c64e3d04ce7d2d85d468a78310755e [formerly 4c6df9daffdfbeb8c7a4aab38bb29997d300861b] [formerly d469d3166a2fb7f8d04e4f69eb8f4ca4ac5c744d [formerly 582027377b7193c9a7fdbb18bd5d39e4e6cfe87e]]
Former-commit-id: 7ebeb17370fd72fb2000f065f21fda03f7497d7f [formerly 008ade0f2e8b7bb97254970ec8a6156ef7859693]
Former-commit-id: 9a6b794cc179b95844899d024c91fe45fa21a339

diff --git a/testing/pbs_test b/testing/pbs_test
--- a/testing/pbs_test
+++ b/testing/pbs_test
@@ -1,12 +1,35 @@
 #!/bin/sh
+#
+# Copyright (c) 2002 The Trustees of Indiana University.  
+#                    All rights reserved.
+# 
+# This file is part of the OSCAR software package.  For license
+# information, see the COPYING file in the top level directory of the
+# OSCAR source distribution.
+#
+# $Id: pbs_test,v 1.6 2002/10/31 15:53:11 jsquyres Exp $
+#
+# Command line arguments:
+#
+# $1: Number of clients
+# $2: Processors per node
+# $3: PBS script to qsub
+# $4: grep string for success
+# $5: output filename prefix
+# $6: timeout scaling factor
+# $7: testprint label
+#
 
-. /etc/profile
+# JMS This seems to do harm -- not sure why it is here...?  The
+# relevant parts of /etc/profile should be run automatically.
+#. /etc/profile
 
 qsub='/opt/pbs/bin/qsub'
 qstat='/opt/pbs/bin/qstat'
-
+exit_status=0
 
 # Check usage (since this can be run seperately)
+
 if [ $# -eq 0 ]; then
   # Get cluster info from user
   echo -n "Enter the number of client nodes: "
@@ -29,7 +52,7 @@ if [ $# -eq 0 ]; then
   read scaling_factor
   opt=${scaling_factor:=3}
 
-  echo -n "Enter a test name (Default is "PBS TEST"): "
+  echo -n "Enter a test name (Default is \"PBS TEST\"): "
   read pbs_test_type
   opt=${pbs_test_type:="PBS TEST"}
 elif [ $# -lt 4 ]; then
@@ -52,7 +75,7 @@ fi
 #echo "output is $output"
 #exit
 
-numprocs=`echo "$clients $ppn * p" | /usr/bin/dc`
+numprocs=`expr $clients \* $ppn`
 script_name=`basename $pbs_script`
 
 function waitexit {
@@ -62,13 +85,13 @@ function waitexit {
           echo ...Hit a key to exit...
           read -n 1 -s  key
         fi
-        exit 0
+        exit $exit_status
 }
 
 function calc_timeout {
   if [ ! $min_timeout ]; then min_timeout=30; fi
   if [ ! $scaling_factor ]; then scaling_factor=3; fi
-  timeout=`echo "$numprocs $scaling_factor * p" | /usr/bin/dc | cut -d . -f 1`
+  timeout=`expr $numprocs \* $scaling_factor`
   if [ $timeout -lt 30 ] || [ $timeout -lt $min_timeout ]; then
     if [ $min_timeout -gt 30 ]; then
       timeout=$min_timeout;
@@ -86,6 +109,7 @@ function check_free_nodes () {
   else
     $OSCAR_TESTPRINT --label "Checking for $clients free nodes:" --fail
     echo Not enough free nodes.  Tests incomplete.
+    exit_status=1
     waitexit
   fi
 }
@@ -126,11 +150,12 @@ pbs_test_routine () {
       if [ $timeleft -eq 0 ]; then  #more than timeout
         $OSCAR_TESTPRINT --label "$pbs_test_type" --fail
         job_state=fail
-        if [ `/opt/pbs/bin/qstat |grep -c $job` -eq 1 ]; then
+	exit_status=1
+        if [ `/opt/pbs/bin/qstat | grep -c $job` -eq 1 ]; then
           /opt/pbs/bin/qdel $job
           sleep 1 # Allows nodes to free up again
         fi
-        if [ $exit_on_fail = yes ]; then waitexit ; fi
+        if [ "$exit_on_fail" = yes ]; then waitexit ; fi
       fi
       timeleft=`expr $timeleft - 1`
     done
@@ -139,5 +164,10 @@ pbs_test_routine () {
   cd ..
 }
 
+# Run the actual test
 
 pbs_test_routine
+
+# Return a meaningful exit status
+
+exit $exit_status
