Update the ssh_user_tests to make more generic (patch from Thilo).
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@8698 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 4da87643a89900ba37ac64020f08abc9be1d5b2e [formerly 9b2921da883e587bb382a122144af95b88a28c14] [formerly 5159d81d058f08435146177ffbdddbcfe7bf6b58 [formerly 07a9728db59009353942f5f48421f85db605db81]] [formerly 9b544bb24f0e198425b06b3e28d456a946a42464 [formerly 6662eed1a0d7c95098b28c11b0e737be1207fd4d] [formerly 9c21dd6c5192585851707328d6beb8417baf3faf [formerly 4eff5a2bd79ae34d4bad14220abc9f70ecdcbf55]]]
Former-commit-id: 3aeed2e2fc8cc58161b1ebe8ba22909670942ba5 [formerly 8b61d55e04d2d9dc117039159a33a9de68bc1e7e] [formerly 1f1ee042b23ebff1e936f7debef07f1779e8ceb1 [formerly 99cdfc8a14e1057bad317028e2bcd67dd361a7aa]]
Former-commit-id: 6b01cc48394dc9a0d6eb60d5920f3ad8de0c8ddc [formerly e8eb00fcc02f968d0caec3e80d3e770a70797c92]
Former-commit-id: e651a5f12cf0a0dc45fcc56c7de76627ea2fac22

diff --git a/testing/ssh_user_tests b/testing/ssh_user_tests
--- a/testing/ssh_user_tests
+++ b/testing/ssh_user_tests
@@ -10,8 +10,14 @@
 # Authors: Jason Brechin
 #          Jeremy Enos
 
+[ -z "${OSCAR_TESTPRINT}" ] && OSCAR_TESTPRINT="./testprint"
 
 node1=$1
+
+if [ -z "${node1}" ]; then
+  echo "ERROR: no node given!"
+  exit 1
+fi
 
 if ping -c 1 $node1 >/dev/null 2>&1
 then
@@ -21,7 +27,7 @@ else
 fi
 
 $OSCAR_TESTPRINT --label "SSH server->node" 
-if ssh $node1 hostname > /dev/null 2>&1
+if ssh -o 'StrictHostKeyChecking no' $node1 hostname > /dev/null 2>&1
 then
   $OSCAR_TESTPRINT --label "SSH server->node" -p 
 else
@@ -30,7 +36,7 @@ fi
 
 $OSCAR_TESTPRINT --label "SSH node->server"  
 server=`hostname`
-if ssh $node1 ssh $server hostname >/dev/null 2>&1
+if ssh $node1 "ssh -o 'StrictHostKeyChecking no' $server hostname >/dev/null 2>&1"
 then
   $OSCAR_TESTPRINT --label "SSH node->server" -p 
 else
