Committed new update-rpms.
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@2359 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: af8d1492ae459652329862662982360c0f1649d5 [formerly d69965a59567822f87a51da6528f41fdb7486a8a] [formerly dca78bb553e01a3ec46a4b6e520527ad8544f80e [formerly 2e90272c7422c4145b6f5e67a76374eca178f781]]
Former-commit-id: 4768c905ae7cd0805ba3b3cd808aa5b65d7fc56d [formerly 1974e31e2b8cc26be1ba6c20fe9eda983dd14bc0]
Former-commit-id: 8c23a66caa147a8df1b6b7f426fd59969ac34739

diff --git a/share/prereqs/update-rpms/scripts/setup b/share/prereqs/update-rpms/scripts/setup
--- a/share/prereqs/update-rpms/scripts/setup
+++ b/share/prereqs/update-rpms/scripts/setup
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Copyright (c) 2003 The Trustees of Indiana University.
 #                         All rights reserved.
@@ -7,7 +7,7 @@
 # information, see the COPYING file in the top level directory of the
 # OSCAR source distribution.
 #
-# $Id: setup,v 1.1 2003/12/09 05:59:00 tuelusr Exp $
+# $Id: setup,v 1.2 2004/02/06 14:47:02 dnl Exp $
 #
 # setup script for the update-rpms package
 #
@@ -17,48 +17,45 @@ VERSION="0.1"
 # initial release
 VERSION="0.2"
 # New version of update-rpms and new directory structure
+VERSION="0.3"
+# David N. Lombard  dnl@speakeasy.net
+# New version of update-rpms
+# script cleanup
 
-VERSION=$(echo "$Revision: 1.1 $" | cut --fields 2 --delimiter " ")
+# What does this do?!
+VERSION=$(echo "$Revision: 1.2 $" | cut --fields 2 --delimiter " ")
 
-PACKAGE="update-rpms"
-echo ${0} | grep -e "/.*/.*" 2>&1 > /dev/null
-if [ $? -ne 0 ]; then
-  MEDIA_DIR="${0%setup}../RPMS"
+PACKAGE=update-rpms
+if [[ $0 = /*/ ]] ; then
+  MEDIA_DIR=${0%/*}/../RPMS
 else
-  MEDIA_DIR="${0%/*/*}/RPMS"
+  MEDIA_DIR=${0%/*/*}/RPMS
 fi
-# For the Bash-impaired, this just uses the location of the setup script,
-# strips off the "/scripts/setup" part and grafts on "/media". The alternative
-# does, anyway. The consequent is an ugly hack I used for testing.
 
-RPM_CACHE="/tftpboot/rpm"
-RPM_DB_DIR="/var/cache/${PACKAGE}"
+RPM_CACHE=/tftpboot/rpm
+RPM_DB_DIR=/var/cache/$PACKAGE
 
-CURRENT=$(ls -1 --sort=version --reverse ${MEDIA_DIR}/${PACKAGE}-*.noarch.rpm |
-	head -1)
+CURRENT=$(ls --sort=version --reverse $MEDIA_DIR/$PACKAGE-*.noarch.rpm | head -1)
 #CURRENT=${CURRENT%.md5sum} # strip any .md5sum suffix
 
-if [ -s ${MEDIA_DIR}/md5sums ]; then
+if [[ -s $MEDIA_DIR/md5sums ]]; then
   echo "Checking MD5 checksums:"
-  (cd ${MEDIA_DIR}
-    md5sum --check md5sums
-  )
-  if [ $? -ne 0 ]; then
-    echo "ERROR: MD5 checksum(s) for ${PACKAGE} don't match"
+  (cd $MEDIA_DIR; md5sum --check md5sums) || {
+    echo "ERROR: MD5 checksum(s) for $PACKAGE don't match"
     exit -1
-  fi
+  }
 else
-  echo "WARNING: No MD5 checksum(s) for ${CURRENT} found"
+  echo "WARNING: No MD5 checksum(s) for $CURRENT found"
 fi
 
-echo "Installing ${CURRENT}"
-rpm --upgrade ${CURRENT}
+echo "Installing $CURRENT"
+rpm --upgrade $CURRENT
 
-mkdir -p ${RPM_DB_DIR}
-if [ -d ${RPM_CACHE} ]; then
+[[ -d $RPM_DB_DIR ]] || mkdir -p $RPM_DB_DIR
+if [[ -d $RPM_CACHE ]]; then
   echo "Creating RPM cache database..."
-  cd ${RPM_DB_DIR}
-  update-rpms --cache=w --url ${RPM_CACHE}
+  cd $RPM_DB_DIR
+  $PACKAGE --cache=u --url $RPM_CACHE
 else
   echo "WARNING: No RPM cache database exists."
   echo "Am I being run from \"install_cluster --> wizard_prep\"?"
