Improved error handling for "make dist". Now it will bail out if something goes wrong.
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@5524 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 6b4203d09824bb1bddba5f9abbfd0c7f49b6ade9 [formerly 6164eea0e90fb7865ee7186b85d5cb255f6e44fa] [formerly 154da281705250cc65bd65d8b7a543e8492eec6a [formerly 8ef37bfa5fa94155ef1b4dd6ed7fc051eac75007]] [formerly 3d43b3a0df86469ca6f305723c7f94ffcdaceeac [formerly 01315088421d37d1f1744628864bf67c4e25adcd] [formerly 6a04f92ccfb3e37f0ad12198d93abbd55ccb086e [formerly 5bcf1617edc0df304ec87b411b56cbe628ec072e]]]
Former-commit-id: 1a480757eb54585191b5019f0a91b33205e8b70a [formerly 42f771f4c4c72d638ff460f29a40626446ccef95] [formerly 64c016e522c04af029dec78f68762f162213dce8 [formerly a7eeec7004e4c631f954f9f646bf3b6669c2ad0d]]
Former-commit-id: 2319e295fdf0c9dddb17831a49c725a05dbadb57 [formerly 9f83b6a0a55856a901d77ef788b112caef50c416]
Former-commit-id: dcd72531340fe7be0b4ece9ffdce9d4a231df4ff

diff --git a/scripts/build_oscar_repo b/scripts/build_oscar_repo
--- a/scripts/build_oscar_repo
+++ b/scripts/build_oscar_repo
@@ -168,9 +168,20 @@ echo "Creating repository metadata"
 case "$PKG" in
     rpm)
 	yume --repo $TARGET --prepare
+	if [ $? -ne 0 ]; then
+	    echo "ERROR: yume execution failed!"
+	    echo "Check for yume, yum, createrepo existence!"
+	    echo "Repository metadata probably wasn't created!"
+	    exit 1
+	fi
 	;;
     deb)
 	rapt --repo $TARGET --prepare
+	if [ $? -ne 0 ]; then
+	    echo "ERROR: rapt execution failed!"
+	    echo "Repository metadata probably wasn't created!"
+	    exit 1
+	fi
 	;;
     *)
 	echo "Unknown packaging system $PKG"
