Added --add option to build_oscar_repo such that one can only add packages to existing repositories instead of replacing them. This mode is needed when adding packages downloaded by OPD. As we don't have the distro packages any more (in a typical user setup), we cannot just reconstruct the repository. This fixes the issue seen by DongInn after step 0 (OPD).
Added pass-through options for --add and --target to prep_oscar_repos. These
are passed to build_oscar_repo.


git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@4837 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 704413b07c274e51e04c198f17f6b35f2e29e306 [formerly 8beaed68d28f55393329a7abc02fea01703da997] [formerly 6c59208cd7a3beeb4095fbb0b61ff9276ac16f66 [formerly 72f9efce9802bea3c0d63b8a76b9bceeab165bfa]] [formerly 6c9cb454e99cf2de79a9ebcd5ca62179a79c10b4 [formerly ca03637040d4c82777a1eeaf4a63e1b568f814a5] [formerly 9e23b468388680c97e4bec16338ceaaa8b61eb85 [formerly a498024a613067c7c7c45e2c20cfac2f3fe8bca6]]]
Former-commit-id: a834519e556631b1ef1633c7bdbb89ff93bb7fa6 [formerly c91653542c2d8c00e11aab9887db0bb55dbbe6b5] [formerly 47682b618fdd45cda26dd301bd82d42dad160ab6 [formerly b1cc27c85a3214ca2b7902f03ad78a137f96f72d]]
Former-commit-id: b1df37d1966e10c70d93cd4abc050281a0ffcdb5 [formerly 66e9ec70822569e3b606386a0ca832a3cc494ff5]
Former-commit-id: afe99c34587fc6eb2c0e2e18ca21058ecbdb4722

diff --git a/scripts/build_oscar_repo b/scripts/build_oscar_repo
--- a/scripts/build_oscar_repo
+++ b/scripts/build_oscar_repo
@@ -11,7 +11,8 @@
 
 usage () {
     echo "Usage:"
-    echo "   $0 --distro|-d DISTRO-VERSION-ARCH --target|-t TARGETDIR"
+    echo "   $0 --distro|-d DISTRO-VERSION-ARCH --target|-t TARGETDIR \ "
+    echo "      [--include SEARCHDIR]"
     echo
     exit 1
 }
@@ -51,6 +52,16 @@ while [ -n "$1" ]; do
        --remove|-r)
 	   shift
 	   REMOVE="1"
+	   ;;
+       --include|-i)          # additional search paths for package RPMs
+	   shift
+	   [ -z "$1" ] && usage
+	   INCLUDE="$INCLUDE $1"
+	   shift
+	   ;;
+       --add|-a)              # only add packages, don't rebuild
+	   shift
+	   ADD_ONLY=1
 	   ;;
        --help|-h)
 	   usage
@@ -99,9 +110,14 @@ if [ -z "$SOURCE" ]; then
     fi
 fi
 
-if [ ! -d "$OHOME/packages/sis/distro/$SOURCE" ]; then
-    echo "Could not find directory $OHOME/packages/sis/distro/$SOURCE"
-    echo "Are you sure the distro $DISTRO is supported???"
+if [ ! -d "$OHOME/packages/sis/distro/$SOURCE" -a -z "$ADD_ONLY" ]; then
+    if [ ! -d "$OHOME/packages/sis/distro" ]; then
+	echo "Could not find directory $OHOME/packages/sis/distro"
+	echo "This should be only run inside a developer checkout!"
+    else
+	echo "Could not find directory $OHOME/packages/sis/distro/$SOURCE"
+	echo "Are you sure the distro $DISTRO is supported???"
+    fi
     exit 10
 fi
 
@@ -111,14 +127,8 @@ fi
 
 TARGET="$TDIR/$DISTRO"
 # check for existence of target directory
-if [ ! -e "$TARGET" ]; then
-    echo "Creating directory $TARGET"
-    mkdir -p $TARGET || {
-	echo "Could not create target directory $TARGET"
-	exit 3
-    }
-else
-    if [ -d "$TARGET" ]; then
+if [ -d "$TARGET" ]; then
+    if [ -z "$ADD_ONLY" ]; then
 	if [ -n "$REMOVE" ]; then
 	    echo "--remove was selected, removing already existing target directory $TARGET"
 	    rm -rf "$TARGET" || {
@@ -130,12 +140,22 @@ else
 	fi
     fi
 fi
+if [ ! -e "$TARGET" ]; then
+    echo "Creating directory $TARGET"
+    mkdir -p $TARGET || {
+	echo "Could not create target directory $TARGET"
+	exit 3
+    }
+fi
 if [ ! -d "$TARGET" -a ! -L "$TARGET" ]; then
     echo "$TARGET is not a directory!"
     exit 5
 fi
 
-SEARCHDIRS="$OHOME/share/prereqs $OHOME/packages /var/lib/oscar/packages"
+SEARCHDIRS="$OHOME/share/prereqs $OHOME/packages"
+if [ -n "$INCLUDE" ]; then
+    SEARCHDIRS="$SEARCHDIRS $INCLUDE"
+fi
 
 cd $OHOME
 echo "Copying packages ..."
