New attempt to fix the issue with Mandriva (bug #280). Should work now.
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@5511 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 8711de551392d453fcc3e2e6f13bb4df2ab6f809 [formerly faa963119a96c0005eb626312ac06d2bc7a6dae5] [formerly cfe9d075c0d2be42afab0f63fd964504cf16c311 [formerly 5b362634c6ac968d569106c019b8ced5677867f1]] [formerly 71b4756f0911e5b8115bd6960dd6745885aef76a [formerly f143fc0b88bdb569e42ef4903ef7be8dbc5d1bcc] [formerly c81c0db98821f732ca51ef8283a87aca3b8320ef [formerly dfd3b1e7a82cf6fe175c922c88a26a05d1ef2c61]]]
Former-commit-id: 2dbfd4b2c3635007f2f0256259d7fa7901c09e0c [formerly b021193832a0fbef05a929d223deb47c62314bb6] [formerly 87170728d66068f4c75b39e57e31e20e4d6ddd9d [formerly 1195d378cec78a829795aedd7090a3f2a480dafb]]
Former-commit-id: 1fd23977f0788fe68aecf5a593b4b56357a504d2 [formerly c5444ccbf99a4df2fa7ece2cb841856c210505f2]
Former-commit-id: 496ab2aec17284c340aaffd25025189c2c23341a

diff --git a/packages/sis/scripts/si_monitor.patch b/packages/sis/scripts/si_monitor.patch
--- a/packages/sis/scripts/si_monitor.patch
+++ b/packages/sis/scripts/si_monitor.patch
@@ -1,27 +1,68 @@
---- /etc/init.d/systemimager-server-monitord     (revision 3797)
-+++ /etc/init.d/systemimager-server-monitord     (working copy)
-@@ -36,6 +36,11 @@
- # default: warning.
- LOGLEVEL=2
-
-+# Check if ithreads are supported.
-+perl -e 'use Config; exit ($Config{useithreads} ne "define");' && \
-+        PERL="`which perl 2>/dev/null`" || \
-+        PERL="`which perl 2>/dev/null` -Mforks -Mforks::shared"
+--- /usr/sbin/si_monitor	(Revision 3797)
++++ /usr/sbin/si_monitor	(Arbeitskopie)
+@@ -151,23 +151,15 @@
+ # Reaping zombie child processes.
+ $SIG{CHLD} = 'IGNORE';
+ 
+-# Start daemon.
+-my $daemon_pid;
+-if ($daemon_pid = fork()) {
+-	# Run in background.
+-	exit(0);
+-} elsif (defined($daemon_pid)) {
+-	setsid or die gmtime() . ": error: can't start a new session: $!\n";
+-	# Create the pid file.
+-	local *FILE;
+-	open(FILE, ">$pid_file") or
+-		die gmtime() . ": error: cannot open file: $pid_file\n";
+-	print FILE "$$\n";
+-	close(FILE);
+-} else {
+-	die gmtime() . ": error: cannot fork daemon process!\n";
+-}
++# Create a new process session.
++setsid or die gmtime() . ": error: can't start a new session: $!\n";
+ 
++# Create the pid file.
++open(FILE, ">$pid_file") or
++	die gmtime() . ": error: cannot open file: $pid_file\n";
++print FILE "$$\n";
++close(FILE);
 +
- case "$1" in
-   start)
-     echo -n "Starting SystemImager's installation monitoring: si_monitor... "
-@@ -44,9 +49,9 @@
+ # Define lock files.
+ my $lock_file = $conf{'lock_dir'} . "/db.si_monitor.lock";
+ 
+--- /etc/init.d/systemimager-server-monitord	(Revision 3797)
++++ /etc/init.d/systemimager-server-monitord	(Arbeitskopie)
+@@ -43,14 +43,28 @@
+         echo -e "failed.\nPID file $PIDFILE exists.  Must be already running."
          exit 1
      fi
++    # Check if ithreads are supported.
++    if perl -e 'use Config; exit ($Config{useithreads} ne "define");'; then
++        SI_MONITOR=`which si_monitor 2>/dev/null`
++    else
++        SI_MONITOR="`which perl 2>/dev/null` -Mforks -Mforks::shared `which si_monitor`"
++        cat << EOF
++
++WARNING: your version of perl doesn't support ithreads!
++
++It's strongly suggested to use a threaded perl (built with 'useithreads').
++
++Falling back to thread emulation via perl-forks...
++EOF
++    fi
      if [ ! -z $LOGFILE ]; then
 -        si_monitor --log $LOGFILE --log_level $LOGLEVEL
-+        $PERL /usr/sbin/si_monitor --log $LOGFILE --log_level $LOGLEVEL
++        $SI_MONITOR --log $LOGFILE --log_level $LOGLEVEL 0>/dev/null >&0 2>&0 &
      else
 -        si_monitor
-+        $PERL /usr/sbin/si_monitor
++        $SI_MONITOR 0>/dev/null >&0 2>&0 &
      fi
      if [ $? -ne 0 ]; then
-
-
+         echo failed.
+-	exit 1
++        exit 1
+     else
+         echo ok.
+     fi
