[opkg-munge] Fix muge configuration: munge.key had bad owner.
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/trunk@10926 18f9d06c-6ae2-0310-8438-938a554feff9

Former-commit-id: 3960aaa12fa83f235a242a705d95861f014739a9 [formerly 58f7ecb9033f937345e6af381a02b0b016913999] [formerly 0f76c04f5eb312dab8fa59f061cba1dbdbb870ad [formerly ee8edb278efd12a67996e87a8a8d1983ef89f6c0]] [formerly c9328fefa7f01ee0344aafa96d60bb6333f646d0 [formerly 8c2879226f2223fdd104a4f9d7e2191dc4d692d5] [formerly 2cb59f39a46b69c8339aa629264845cc5f4aad5f [formerly 82fe286a00ca5672f85d3dc11e6a3ce40ee45d96]]]
Former-commit-id: f277247256ea7927fb5883ed13ce8c08d50f897a [formerly f9ad06f13091d6c4ec6597077384f2a9abc5b3ef] [formerly 2aec22ed218b651e11465c1ffe9e59a97a8d9117 [formerly 078a1eb2be7c2ac9d8a8e69edcd5269a5c16db1d]]
Former-commit-id: 975fe697a3dc5527a4982418519f71669bd05d30 [formerly 9dc4011f3e5b79bfca50703a1acc2cf8816d0749]
Former-commit-id: 9b96d9747516e58b52e4245c5707048f50a7dd40

diff --git a/packages/munge/scripts/api-post-image b/packages/munge/scripts/api-post-image
--- a/packages/munge/scripts/api-post-image
+++ b/packages/munge/scripts/api-post-image
@@ -30,8 +30,20 @@ if [ -z "$IMAGEDIR" -o ! -d "$IMAGEDIR" ]; then
     exit 1
 fi
 
+if test ! -r /etc/munge/munge.key
+then
+	echo "ERROR: Unable to update image $IMAGEDIR with munge key: key not found"
+	exit 1
+fi
+
+# Install server munge key into the image.
+/bin/mkdir -p ${IMAGEDIR}/etc/munge
+/bin/cp -f /etc/munge/munge.key ${IMAGEDIR}/etc/munge/
+
 # Get helper path: fix-munge-config
 MUNGE_OPKG_DIR=$(basename $0)
+
+# Fix munge configuration and security.
 if test -x ${MUNGE_OPKG_DIR}/fix-munge-config
 then
 	${MUNGE_OPKG_DIR}/fix-munge-config $IMAGEDIR
@@ -39,12 +51,4 @@ else
 	/usr/lib/oscar/packages/munge/fix-munge-config $IMAGEDIR
 fi
 
-if test ! -r /etc/munge/munge.key
-then
-	echo "ERROR: Unable to update image $IMAGEDIR with munge key: key not found"
-	exit 1
-fi
 
-/bin/cp -f /etc/munge/munge.key ${IMAGEDIR}/etc/munge/
-/bin/chown $MUNGE_UID.$MUNGE_GID ${IMAGEDIR}/etc/munge/munge.key
-/bin/chmod 600 ${IMAGEDIR}/etc/munge/munge.key
